### ISSUE TITLE
Craft CMS Admin Panel not accessible after 2.01 update

### ISSUE THREAD

**Issue by playwellsteve** [laravel/valet#244]
After updating to valet 2.01, all of the links on the front end of the site are working, but attempting to access the control panel gives me the following error:

Can’t run Craft CMS :(

Your server doesn’t meet the following requirements to run Craft CMS:

Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.
Please talk to your host/IT department about upgrading your server.

There are no errors in nginx-error.log that correspond to the Craft errors. I've rebooted my machine, and nginx was not installed prior to the valet update.

**Comment by playwellsteve** [comment]
Here is an interesting twist:
Visiting the CP using "craftcms.dev/admin"  throws the error above
visiting the CP using "craftcms.dev/index.php?p=admin" works, and after doing this "craftcms.dev/admin" works -- even in other browsers.

**Comment by mmikkel** [comment]
Setting `$_SERVER['PHP_SELF']` to the same value as `$_SERVER['SCRIPT_NAME']` seems to fix the issue. I'll put up a pull request ASAP.

**Comment by ryanscherler** [comment]
Even after upgrading to the latest version of Valet (with this fix in the driver) I am still experiencing this issue. Am I missing something?

**Comment by ryanscherler** [comment]
Seems this issue is fixed with latest Craft update (https://craftcms.com/changelog#2-6-2957 )

Sorry about that!

**Comment by iparr** [comment]
This unfortunately still exists for me.

When I use `index.php?p=admin` I get the following message:

> ### Can’t run Craft CMS :(
>
> Your server doesn’t meet the following requirements to run Craft CMS:
>
> *
>
> Please talk to your host/IT department about upgrading your server.

Please note: That blank bullet point is not a formatting error! It really does just return a blank bulletpoint - perhaps not the fault of *Valet* admittedly, but everything has been otherwise fine when using *Homestead*

**Comment by isaachvazquez** [comment]
@iparr Any luck getting this to work? I'm having the same issue with the blank bullet point.

**Comment by iparr** [comment]
None at all I'm afraid. I've slunk off back to *Vagrant*.

**Comment by isaachvazquez** [comment]
Are you getting it to work with Vagrant? That's what I'm using and I'm still getting this.

**Comment by iparr** [comment]
What? Craft CMS generally? Yes. It has been working fine.

IIRC I was presented with some bullet points that contained modules that I had to install, but there were not blank mystery bullet-points.

**Comment by takobell** [comment]
@isaachvazquez @iparr We've fixed that missing requirement message for the next Craft release.  Most likely you're missing the mcrypt extension (no longer bundled by default in PHP 7.1).  `sudo apt-get install mcrypt php7.1-mcrypt` should get you going.

**Comment by iparr** [comment]
Thanks @takobell - I recall when I was getting Craft working on Vagrant it did specifically ask for Mcrypt.

Regardless, as this is Valet and I'm on a Mac I can't use `apt-get`, but I did install that extension using Brew. It says it's installed and it was displaying that blank bullet point then.

(All this said, I'm at a stage now where I can't even get Valet to serve me error pages, let alone a fully working CMS so maybe I'll just return when things are a little further along!)

**Comment by joshmanders** [comment]
`brew install php71-mcrypt` and then `brew services restart php71`

**Comment by iparr** [comment]
Sorry for not being clear @joshmanders , but yes - that's exactly what I did.

**Comment by joshmanders** [comment]
Try restarting, sometimes Mac gets wonky and a restart fixes it (Had a few instances like this even while working on Valet)

**Comment by iparr** [comment]
Thanks. I did that, and what I think I'm needing to do is use `brew services start` to load some services in a particular order: loading `sudo brew service start dnsmasq` first before then doing a `valet start` without sudo.

I still need to do @playwellsteve 's suggestion (`/index.php?p=admin`) , but otherwise we're in.

I have a multi-environment *Craft* config, that uses the following:

```
'.dev' => array(
		'server' => 'localhost',
		'database' => '5m-craft',
		'user' => 'root',
		'password' => ''
	),
```

…to connect to this local development server. However, it only works (i.e. actually connects to the DB) if I change `.dev` to `*`, which suggests that *Craft* doesn't know it's on a `.dev` address - which might explain the aforementioned URL problems. I suppose this is another issue for another ticket!
