### ISSUE TITLE
404 for files in public/ (LaravelValetDriver)

### ISSUE THREAD

**Issue by skollro** [laravel/valet#375]
I always get a status code 404 for existing files which are directly located under public/ on a fresh install (favicon.ico, robots.txt), but the files are delivered. If I name them differently, it's working with a 200. Files in subdirectories css/, js/ are served properly with a status code 200.

Edit: I figured out that the problem is located in the Nginx config. If I comment out these lines, favicon.ico and robots.txt are served.

```
location = /favicon.ico { access_log off; log_not_found off; }
location = /robots.txt  { access_log off; log_not_found off; }
```

**Comment by simensen** [comment]
I just spent half an hour trying to figure out what was wrong with my favicon for my new spark project served behind valet. I'd be happy to figure out how to patch this if someone could point me in the right direction.

**Comment by adamwathan** [comment]
I feel like I fixed this on the master branch a few months back, are you
running dev-master or latest tag?

**Comment by simensen** [comment]
hm. let me see. it looks like i was one version back. the problem i'm having might be slightly different. commenting out the lines mentioned above didn't fix my problem. my problem is that getting /favicon.ico returns the actual image but gives status 404. so if i visit /favicon.ico in the browser directly, it renders just fine.

**Comment by adamwathan** [comment]
Yeah that should be fixed, but if you are using local SSL on that site you'll need to resecure that site to generate an updated nginx config.

**Comment by adamwathan** [comment]
Quick trick to regenerate configs for any SSL sites:

```
valet domain blah
valet domain dev
```

**Comment by simensen** [comment]
cool, thanks. i'm not doing local ssl. or rather, wasn't. just tried "valet secure mudskipper-dev" and it worked like a charm. loving valet even more now. :) thanks for your help!

also, for the record, i did an update from valet v2.0.4 to v2.0.5 and it all looks good now.

**Comment by adamwathan** [comment]
Sweet!

**Comment by nickdekruijk** [comment]
I'm still having this issue. Just upgraded to v2.8.1 and still favicon.ico and my https://project.test/ is giving a 404 error on favicon, but opening https://project.test/favicon.ico directly does seem to work.

**Comment by stidges** [comment]
It seems the issue with favicon.ico / robots.txt was fixed in [this commit](https://github.com/laravel/valet/commit/fda0d3440de216a8cd6bcac0090b3bc4dd217d55) (v2.0.5) but was later re-introduced in #819 (v2.4.1). To work around this I have removed the favicon.ico and robots.txt location blocks from my Nginx configuration.

**Comment by 100phel** [comment]
I'm having the same issue.

**Comment by mattstauffer** [comment]
@stidges Great catch there. That's a fascinating issue... I'm curious how we can get rid of the error logs but also make it work

**Comment by nickdekruijk** [comment]
I'm not a nginx expert unfortunately but what happens if you only have 
`location = /favicon.ico { access_log off }` ?
So only turning of access logging but nog error log? All sites should have a working favicon these days anyway else they will see 404 errors when the site goes live.

**Comment by 100phel** [comment]
The issue is not limited to favicon.ico and robots.txt. I also get 404 for:
```
http://project.test/js/app.js
http://project.test/css/app.css
```

**Comment by AlexMartinFR** [comment]
Also stumbled on this issue today, here is my workaround for now:

Nginx is looking for a _favicon.ico_ file at the root level.
Instead, for Laravel projects, it should look in the public folder.

Just add **/public** on the files paths inside your config file, and run `valet restart`:
```
location = /public/favicon.ico { access_log off; log_not_found off; }
location = /public/robots.txt  { access_log off; log_not_found off; }
```

If you have run `valet secure`, you'll find your app's config file here: `~/.config/valet/nginx/your_app.test`

Otherwise, the default valet nginx config file is located here:
`/usr/local/etc/nginx/valet/valet.conf`

It might make more sense to edit it on a project basis, in case you don't only serve Laravel apps with Valet.

**Comment by snapey** [comment]
@AlexMartinFR solution worked for me but only after I found a copy of valet.conf in /opt/homebrew/etc/nginx/valet

I guess it depends how you installed

**Comment by zatorck** [comment]
Hello All. 

Nice that I found this thread. I got very similar strange problem only for files located in root of public Symfony project, because it's not working for me on very legacy symfony 3.2 project but only if I do XMLHttpRequest or jQuery, but if I go to link directly in Chrome it works (by clicking on "open in new tab").

**Comment by shengslogar** [comment]
Still having this issue on Laravel Valet 3.3.2. Could we get this issue reopened?

I'm unclear to me what the underlying cause is here but commenting out the `location = /favicon.ico` line as described in previous comments works for me. It's baffling that the browser 404s while also loading the file at the same time (at least looking at both Chrome and Firefox consoles), and directly accessing the URL works.

![Screenshot 2023-03-08 at 20 27 41@2x](https://user-images.githubusercontent.com/4350009/223842555-8d977b2d-7d18-43fd-985f-9895d5307f0a.jpg)

**Comment by simensen** [comment]
@shengslogar I wonder if this is a simple order-of-operations issue? Can you try putting the unmodified favicon/robots directives *before* the root redirect/last directive?

```
location /some-valet-uuid-directory-path/ {
    internal;
    alias /;
    try_files $uri $uri/;
}

location = /favicon.ico { access_log off; log_not_found off; }
location = /robots.txt  { access_log off; log_not_found off; }

location / {
    rewrite ^ "/Users/sheng/.composer/vendor/laravel/valet/server.php" last;
}
```

Since that root-level rewrite has `last` at the end, I'm wondering if those locations are being applied after the fact?

It looks like the way `serveStaticFile` works (https://github.com/laravel/valet/blob/d1967bbd0c61e528e47a79ed45556e58c2e614cf/cli/Valet/Drivers/ValetDriver.php#L137) is by doing an internal redirect to include that /some-valet-uuid-directory-path prefix.

Maybe it won't matter, but might be worth a try? Would involve not changing the "standard" way to silence favicon and robots without other weird side effects like serving the file with a 404 or NOT serving a file and still having a 200/204 response which would likely confuse people for the same reason.

**Comment by shengslogar** [comment]
@simensen I think this should work, but only because the final `location` block would override the previous? Wait... but that  doesn't make sense, since `location /some-valet-uuid-directory-path/ { }` is at the very top... Are they supposed to be merged together? Will try playing with this later today.

**Comment by shengslogar** [comment]
@simensen Moving those blocks above yields the same weird 404-but-directly-accessible behavior.

**Comment by Stetzon** [comment]
for anyone using Laravel Herd (which uses Valet under the hood) the nginx config files are located in `~/Library/Application Support/Herd/config`.  The favicon lines in question are in `herd.conf`

**Comment by NickSdot** [comment]
For me it was simply removing the leading `/` in the relevant configs..

```diff
-location = /favicon.ico { access_log off; log_not_found off; }
+location = favicon.ico { access_log off; log_not_found off; }
-location = /robots.txt  { access_log off; log_not_found off; }
+location = robots.txt  { access_log off; log_not_found off; }
```
