### ISSUE TITLE
Since upgrading to 2.1.6, WP-Cron (at least) does not work; cannot resolve domain

### ISSUE THREAD

**Issue by jonathanstegall** [laravel/valet#712]
I'm running Valet with WordPress. I use the [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/) plugin to monitor cron jobs. Since updating the other day, none of my cron jobs run.

The WP Crontrol admin page (/wp-admin/tools.php?page=crontrol_admin_manage_page) reports this on multiple Valet sites:

> There was a problem spawning a call to the WP-Cron system on your site. This means WP-Cron events on your site may not work. The problem was: 
> cURL error 6: Could not resolve: mydomain.test (Domain name not found)

At first I thought this might be related to upgrading PHP to 7.3, but it also happens when I downgrade back to 7.1. On previous Valet versions (running PHP 7.1) I was able to successfully run cron jobs.

In case it's relevant, these sites are running on HTTPS.

**Comment by drbyte** [comment]
1. What version of Valet did you upgrade from? (ie: let's investigate whether this is actually caused by Valet, and if so, by which version, or even better, which commit)

2. Can you update the title of this Issue to reflect that this is related to `WP-Cron` and not imply "nobody's cron will ever work"? It'd be nice if it also mentioned "could not resolve domain name", but there's probably not room for that.


The CURL error message is the critical part. When CURL says it cannot resolve a domain, it suggests a DNS issue. When you upgraded Valet, did you also upgrade dnsmasq?

Is there any problem resolving any of your .test sites in your browser?  
Is the site in the error message the same URL as your app? (I've seen where they "were" different, but only in a tiny typo way that was obscure)

If perchance it's an SSL certificates thing connected to CURL, and not actually a DNS resolution thing, you could try adding a `.curlrc` text file in your home directory (ie: `~/.curlrc`), containing:
`cacert=/Users/YOUR_NAME_HERE/.config/valet/CA/LaravelValetCASelfSigned.pem`
(and replace YOUR_NAME_HERE with your home directory's username)
This will allow the CURL client to find the CA Certificates for Valet.

**Comment by jonathanstegall** [comment]
@drbyte thanks for your help.

1. Apologies, I don't remember which version I was running. I want to say it was 2.0.3, but I might be confusing that. I am very confident it was above version 2.0, but I'm not so confident aside from that.
2. I tried to update the title to be more specific, thanks
3. I probably did update dnsmasq, but I don't remember running a command specifically to that effect. It maybe came through composer though? dnsmasq reports itself as version 2.80.
4. I did have some 502 errors on .test sites when I tried switching to PHP 7.1 and then back to PHP 7.3, but when I ran `sudo brew services restart nginx && sudo brew services restart php@7.3` and then `valet install` to make sure, they all began working again. But this did not have any impact on the curl message.
5. Yes, the error message site is identical. For example, `vanilla-wordpress.test` appears in the error message and in the browser URL bar. I *am* able to run `curl https://vanilla-wordpress.test` and get a successful response in the command line, in case that is relevant.
6. I tried adding the `.curlrc` file as you mentioned (replacing YOUR_NAME_HERE with my user) and I ran `valet restart` but this did not have an impact.

**Comment by drbyte** [comment]
Given you say CURL is working fine from the command line, and websites open okay generally, the core valet functions are operating properly.

It may be necessary to study the DNS Lookup configuration/implementation in wp-cron (probably in whatever code it uses to invoke CURL) to understand more about what could be interfering.

**Comment by AlexECP** [comment]
Im having the same problem, it also coincided with upgrading to php7.3.  After not being able to resolve it after searching and trying things for a few hours, and since I had been planning to do a clean install of OSX Mojave anyway, I did just that.  Complete fresh install, same issue.  If I add the domain directly to `/etc/hosts` it works... but hoping for a better workaround

**Comment by jonathanstegall** [comment]
@AlexECP didn't think of that at all, but I notice that adding the domain to `/etc/hosts` seems to work for me as well (after also running `sudo killall -HUP mDNSResponder;`). Thanks for mentioning that.

**Comment by AlexECP** [comment]
Just found that if I set the first dns in my network preferences to `127.0.0.1`, and then after that my regular DNSs, it works without needing to edit `/etc/hosts`.  Thats good enough for me for now, but it sure is a strange problem.

**Comment by drbyte** [comment]
That seems to point even more directly at the code that wp-cron is using to do its calls (and specifically whatever that code then uses to do its DNS lookups).

**Comment by AlexECP** [comment]
I was having the issue with non wordpress projects.

**Comment by raftalks** [comment]
I have come across same issue, I can curl from terminal to any website on the web but cannot resolve the domain to any valet domain set on my machine. This issue is now stopping me from working on microservices of laravel apps that talks to each other.

**Comment by drbyte** [comment]
If you've tinkered with the DNS settings in your Mac then dnsmasq may have difficulties, and your "disabling wifi makes it work" suggests that DNS Servers may be customized.
 In those situations it's best to start with removing ALL dns server entries, and just leave 127.0.0.1 like this:

<img width="334" alt="screen shot 2019-02-07 at 11 00 56 pm" src="https://user-images.githubusercontent.com/404472/52458244-4e140100-2b2c-11e9-80e4-c348260afba3.png">

I'm in the habit of then adding a custom dnsmasq config to tell it to use 1.1.1.1 if it can't find a desired result locally. You could just add 1.1.1.1 to your Mac's DNS Servers list, ie: into the screenshot above.

I've run `brew upgrade` a lot and valet, including dnsmasq, works fine for the many projects I'm working on, including those that do custom CURL calls, as well as via packages like Guzzle.

**Comment by abepark01** [comment]
RE: https://github.com/laravel/valet/issues/712#issuecomment-461359234

I can confirm this too.
OSX High Sierra 10.13.6
PHP 7.3.2
Laravel Valet 2.2.1
nginx/1.15.8

When I add the valet domain to `/etc/hosts/` I am able to run curl inside the wordpress plugin installer

> I have come across same issue, I can curl from terminal to any website on the web but cannot resolve the domain to any valet domain set on my machine. This issue is now stopping me from working on microservices of laravel apps that talks to each other.
> 
> I have run the following code to test this issue:
> 
> ```
> $_h = curl_init();
>     curl_setopt($_h, CURLOPT_HEADER, 1);
>     curl_setopt($_h, CURLOPT_RETURNTRANSFER, 1);
>     curl_setopt($_h, CURLOPT_HTTPGET, 1);
>     curl_setopt($_h, CURLOPT_URL, 'https://{YOUR VALET DOMAIN HERE}.test'); // This doesn't work
> //    curl_setopt($_h, CURLOPT_URL, 'https://google.com'); // This works
>     curl_setopt($_h, CURLOPT_DNS_USE_GLOBAL_CACHE, false );
>     curl_setopt($_h, CURLOPT_DNS_CACHE_TIMEOUT, 2 );
> 
>     var_dump(curl_exec($_h));
>     var_dump(curl_getinfo($_h));
>     var_dump(curl_error($_h));
> ```
> # update
> If I disable the network (Wifi/Ethernet) on OSX Mojave 10.14.2
> the valet domain do gets resolved without any issue.
> I have downgraded valet to 2.1 but same issue.
> I am assuming dnsmasq is not able to work properly after running brew upgrade

**Comment by simonhamp** [comment]
I did a brew upgrade recently and I experienced a similar problem. For some reason the only way I've been able to resolve it is to explicitly define my DNS servers in network config, using 127.0.0.1 as the primary DNS server and my default ones as secondary ones.

Super annoying

**Comment by simonhamp** [comment]
My only fix so far is:
```
cp /usr/local/etc/openssl/cert.pem /usr/local/etc/openssl/cert.pem.bak && cat ~/.config/valet/CA/LaravelValetCASelfSigned.pem >> /usr/local/etc/openssl/cert.pem
```
This makes a backup of the `cert.pem` (the Root CA file used by curl if you've installed PHP via Homebrew) and then appends the Valet CA certificate to the main cert.pem.

Doing this, I haven't needed any customisations to my `php.ini` or anything special in my `~/.curlrc`

**Comment by rosswintle** [comment]
Just wanted to add that I'm was also experiencing this. But it seems to have been fixed by some of the many updates that I did today.

I was on v2.3.3 and just today realised that "loopback" http requests from WordPress to run things like WP Cron and for internal processes accessing WordPress itself over the API. I can also see this in Tools -> Site Health

https://share.getcloudapp.com/YEudOpdO

Today I've done the very long and convoluted process of:

 - Updating brew
 - Updating openssl
 - Updating php (I'm now on 7.2.26)
 - Updating nginx (I'm now on 1.17.7)
 - Updating mariadb
 - Updating valet (I'm now on 2.7.1)

and it's now...well, it's not fine, it's giving me connection timeouts. 

But something in this chain of updates seems to have fixed it.

This is all on MacOS Catalina 10.15

**Comment by drbyte** [comment]
Is the original problem in this Issue still a problem with current Valet version and updated Brew dependencies?

**Comment by rosswintle** [comment]
As far as I can tell updating everything to latest versions fixes the issue. I would close it.

**Comment by mattstauffer** [comment]
Closing for now. Please feel free to re-open if you're still having this.

**Comment by lonnylot** [comment]
I am still having this issue.

- OSX 10.15.1
- PHP 7.4.1
- Valet 2.8.1

**Comment by drbyte** [comment]
One approach I've found that may help is to follow the instructions provided by Homebrew's OpenSSL recipe:

> RECIPE COMMENTS:
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs
>
> and run
  /usr/local/opt/openssl@1.1/bin/c_rehash


INSTRUCTIONS FOR VALET:
1. `valet install` of course
2. `valet secure` for at least one site (it needs to generate its CA)
3. Run the following:
```bash
cp ~/.config/valet/CA/LaravelValetCASelfSigned.pem /usr/local/etc/openssl@1.1/certs
/usr/local/opt/openssl@1.1/bin/c_rehash
```
(If for some reason you're using openssl 1.0 then the `@1.1` in both commands may need to be omitted)
